name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build TypeScript
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Set correct MIME types
        run: |
          echo "Setting correct MIME types for JavaScript files"
          find ./dist -name "*.js" -type f -exec echo "Processing {}" \;

      - name: Ensure all required files exist
        run: |
          echo "Checking for required files"
          if [ ! -f "./dist/index-nomodule.html" ]; then
            echo "index-nomodule.html not found, copying from template"
            cp ./dist/index.html ./dist/index-nomodule.html
          fi
          if [ ! -f "./dist/.nojekyll" ]; then
            echo "Creating .nojekyll file"
            touch ./dist/.nojekyll
          fi
          if [ ! -f "./dist/CNAME" ]; then
            echo "Creating CNAME file"
            echo "sigsolutions.co.za" > ./dist/CNAME
          fi

          # Copy JavaScript files to the correct location
          echo "Copying JavaScript files to the correct location"
          mkdir -p ./dist/js
          cp ./dist/js/*.js ./dist/js/ || true

          # Copy index-redirect.html to the root
          echo "Copying index-redirect.html to index.html"
          cp ./index-redirect.html ./dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
